site_name: OWASP Top 10:2025
site_description: OWASP Top 10:2025
repo_name: OWASP/Top10
repo_url: https://github.com/OWASP/Top10
copyright: © Copyright 2021-2025 - OWASP Top 10 Team - This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.en_US">Creative Commons Attribution 3.0 Unported License</a>.
docs_dir: docs
theme:
  name: material
  language: en
  logo: assets/OWASP_Logo_Transp.png
  features:
    - navigation.sections
    - navigation.instant
    - search.suggest

nav:
  - Home: 'index.md'
  - About OWASP: '2025/0x01_2025-About_OWASP.md'
  - What are Application Security Risks?: '2025/0x02_2025-What_are_Application_Security_Risks.md'
  - Establishing a Modern Application Security Program: '2025/0x03_2025-Establishing_a_Modern_Application_Security_Program.md'
  - Top 10:2025 List:
    - A01 Broken Access Control: '2025/A01_2025-Broken_Access_Control.md'
    - A02 Security Misconfiguration: '2025/A02_2025-Security_Misconfiguration.md'
    - A03 Software Supply Chain Failures: '2025/A03_2025-Software_Supply_Chain_Failures.md'
    - A04 Cryptographic Failures: '2025/A04_2025-Cryptographic_Failures.md'
    - A05 Injection: '2025/A05_2025-Injection.md'
    - A06 Insecure Design: '2025/A06_2025-Insecure_Design.md'
    - A07 Authentication Failures: '2025/A07_2025-Authentication_Failures.md'
    - A08 Software or Data Integrity Failures: '2025/A08_2025-Software_or_Data_Integrity_Failures.md'
    - A09 Logging and Alerting Failures: '2025/A09_2025-Logging_and_Alerting_Failures.md'
    - A10 Mishandling of Exceptional Conditions: '2025/A10_2025-Memory_Management_Errors.md'
  - Next Steps: '2025/A11_2025-Next_Steps.md'

markdown_extensions:
  - attr_list

plugins:
  - search
  - i18n:
      default_language: en
      docs_structure: folder
      material_alternate: true
      reconfigure_material: true
      languages:
        - locale: en
          default: true
          name: en - English
          build: true
      nav_translations:

        SAMPLE:
          Home: Startseite
          Notice: Anmerkung
          Introduction: Einführung
          How to use the OWASP Top 10 as a standard: Wie man die OWASP Top 10 als Standard verwendet
          How to start an AppSec program with the OWASP Top 10: Wie man ein AppSec-Program mit den OWASP Top 10 beginnt
          About OWASP: Über OWASP
          Top 10:2025 List: Liste der Top 10:2025
          A01 Broken Access Control: A01 - Mangelhafte Zugriffskontrolle
          A02 Cryptographic Failures: A02 - Fehlerhafter Einsatz von Kryptographie
          A03 Injection: A03 - Injection
          A04 Insecure Design: A04 - Unsicheres Anwendungsdesign
          A05 Security Misconfiguration: A05 - Sicherheitsrelevante Fehlkonfiguration
          A06 Vulnerable and Outdated Components: A06 - Unsichere oder veraltete Komponenten
          A07 Identification and Authentication Failures: A07 - Fehlerhafte Authentifizierung
          A08 Software and Data Integrity Failures: A08 - Fehlerhafte Prüfung der Software- und Datenintegrität
          A09 Security Logging and Monitoring Failures: A09 - Unzureichendes Logging und Sicherheitsmonitoring
          A10 Server Side Request Forgery (SSRF): A10 - Server-Side Request Forgery (SSRF)
          Next Steps: Nächste Schritte
  - macros:     # needs to be the last plugin to export the final osib-YAML file for all languages
      module_name: '../osib/osib_macro'
      include_dir: '../osib/include'
      verbose: false                                                  # debug
      on_error_fail: true
extra:
  alternate:                                                         # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector
    - name: en - English
      link: ./en/
      lang: en
    - name: de - Deutsch
      link: ./de/
      lang: de
  osib:
    document:     osib.owasp.top10
    version:      2025-0-1
#    document:     <osib-id>                    # e.g. osib.owasp.top10
#    version:      <version-no, no dots '.'>    # e.g. 4-0, 2025-1-0
    categories:   [document, awareness]        # list of all default categories
    default_lang: en
    yaml_file:    ../osib/include/osib.yml
    export_dir:   ../osib/export
    latest:       2                            # 2: add the latest version(s), if successor(s) exist, log an info
    debug:        0                            # debug level (0-3); default is 2
    cre:          osib.owasp.cre.1-0
    successor_texts:
      en:         successor
      de:         Nachfolger
    split_to_texts:
      en:         split to
      de:         Aufgeteilt in
