site_name: OWASP Top 10:2021
site_description: OWASP Top 10:2021
repo_name: OWASP/Top10
repo_url: https://github.com/OWASP/Top10
copyright: © Copyright 2021 - OWASP Top 10 team - This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.en_US">Creative Commons Attribution 3.0 Unported License</a>.
docs_dir: docs
theme:
  name: material
  language: en
  logo: assets/OWASP_Logo_Transp.png
  features:
    - navigation.sections

nav:
  - Home: index.md
  - Notice: '0x00-notice.md'
  - Introduction: 'A00_2021_Introduction.md'
  - How to use the OWASP Top 10 as a standard: 'A00_2021_How_to_use_the_OWASP_Top_10_as_a_standard.md'
  - How to start an AppSec program with the OWASP Top 10: 'A00_2021-How_to_start_an_AppSec_program_with_the_OWASP_Top_10.md'
  - About OWASP: 'A00-about-owasp.md'
  - Top 10:2021 List:
    - A01 Broken Access Control: 'A01_2021-Broken_Access_Control.md'
    - A02 Cryptographic Failures: 'A02_2021-Cryptographic_Failures.md'
    - A03 Injection: 'A03_2021-Injection.md'
    - A04 Insecure Design: 'A04_2021-Insecure_Design.md'
    - A05 Security Misconfiguration: 'A05_2021-Security_Misconfiguration.md'
    - A06 Vulnerable and Outdated Components: 'A06_2021-Vulnerable_and_Outdated_Components.md'
    - A07 Identification and Authentication Failures: 'A07_2021-Identification_and_Authentication_Failures.md'
    - A08 Software and Data Integrity Failures: 'A08_2021-Software_and_Data_Integrity_Failures.md'
    - A09 Security Logging and Monitoring Failures: 'A09_2021-Security_Logging_and_Monitoring_Failures.md'
    - A10 Server Side Request Forgery (SSRF): 'A10_2021-Server-Side_Request_Forgery_(SSRF).md'
  - Next Steps: 'A11_2021-Next_Steps.md'

markdown_extensions:
  - attr_list

plugins:
  - i18n:
      default_language: en
      docs_structure: suffix
      material_alternate: true
      reconfigure_material: true
      languages:
        en: en - English
        ar: ar - العربية
        de: de - Deutsch
        es: es - Español
        fr: fr - Français
        id: id - Indonesian
        it: it - Italiano
        ja: ja - 日本語
        pt_BR: pt_BR - Português (Brasil)
        zh_CN: zh_CN - 简体中文
        zh_TW: zh_TW - 繁體中文
      nav_translations:
        ar:
          Home: الصفحة الرئيسية
          Notice: ملاحظات
          Introduction: المقدمة
          How to use the OWASP Top 10 as a standard: كيف تستخدم إطار أعلى عشرة مخاطر من أواسب كنموذج معياري.
          How to start an AppSec program with the OWASP Top 10: كيف تبدأ امن التطبيقات مع أعلى عشرة مخاطر من أواسب
          About OWASP: عن أواسب
          Top 10:2021 List:   قائمة اعلى عشرة مخاطر لعام 2021
          A01 Broken Access Control: A01 تخطي صلاحيات الوصول
          A02 Cryptographic Failures: A02 فشل آلية التشفير
          A03 Injection: A03 الحقن
          A04 Insecure Design: A04 التصميم الغير آمن
          A05 Security Misconfiguration: A05 الإعدادات الأمنية الخاطئة
          A06 Vulnerable and Outdated Components: A06 الثغرات و المكونات الغير المحدثة
          A07 Identification and Authentication Failures: A07 الهوية و فشل عملية التحقق
          A08 Software and Data Integrity Failures: A08  فشل سلامة البيانات والبرمجيات
          A09 Security Logging and Monitoring Failures: A09 فشل في تسجيل السجلات الأمنية والمراقبة
          A10 Server Side Request Forgery (SSRF): A10 تزوير الطلبات من جانب الخادم SSRF
          Next Steps: الخطوات المقبلة
        de:
          Home: Startseite
          Notice: Anmerkung
          Introduction: Einführung
          How to use the OWASP Top 10 as a standard: Wie man die OWASP Top 10 als Standard verwendet
          How to start an AppSec program with the OWASP Top 10: Wie man ein AppSec-Program mit den OWASP Top 10 beginnt
          About OWASP: Über OWASP
          Top 10:2021 List: Liste der Top 10:2021
          A01 Broken Access Control: A01 - Mangelhafte Zugriffskontrolle
          A02 Cryptographic Failures: A02 - Fehlerhafter Einsatz von Kryptographie
          A03 Injection: A03 - Injection
          A04 Insecure Design: A04 - Unsicheres Anwendungsdesign
          A05 Security Misconfiguration: A05 - Sicherheitsrelevante Fehlkonfiguration
          A06 Vulnerable and Outdated Components: A06 - Unsichere oder veraltete Komponenten
          A07 Identification and Authentication Failures: A07 - Fehlerhafte Authentifizierung
          A08 Software and Data Integrity Failures: A08 - Fehlerhafte Prüfung der Software- und Datenintegrität
          A09 Security Logging and Monitoring Failures: A09 - Unzureichendes Logging und Sicherheitsmonitoring
          A10 Server Side Request Forgery (SSRF): A10 - Server-Side Request Forgery (SSRF)
          Next Steps: Nächste Schritte
        es:
          Home: Inicio
          Notice: Notas
          Introduction: Introducción
          How to use the OWASP Top 10 as a standard: Cómo utilizar el OWASP Top 10 como un estándar
          How to start an AppSec program with the OWASP Top 10: Cómo iniciar un programa de AppSec con el OWASP Top 10
          About OWASP: Acerca de OWASP
          Top 10:2021 List: 'Top 10: Lista 2021'
          A01 Broken Access Control: A01 Pérdida de Control de Acceso
          A02 Cryptographic Failures: A02 Fallas Criptográficas
          A03 Injection: A03 Inyección
          A04 Insecure Design: A04 Diseño Inseguro
          A05 Security Misconfiguration: A05 Configuración de Seguridad Incorrecta
          A06 Vulnerable and Outdated Components: A06 Componentes Vulnerables y Desactualizados
          A07 Identification and Authentication Failures: A07 Fallas de Identificación y Autenticación
          A08 Software and Data Integrity Failures: A08 Fallas en el Software y en la Integridad de los Datos
          A09 Security Logging and Monitoring Failures: A09 Fallas en el Registro y Monitoreo
          A10 Server Side Request Forgery (SSRF): A10 Falsificación de Solicitud del Lado del Servidor (SSRF)
          Next Steps: Próximos pasos
        fr:
          Home: Page d'accueil
          Notice: Note
          Introduction: Introduction
          How to use the OWASP Top 10 as a standard: Comment utiliser le Top 10 OWASP comme standard
          How to start an AppSec program with the OWASP Top 10: Comment démarrer un programme SecApp avec l'OWASP Top 10
          About OWASP: À propos de l'OWASP
          Top 10:2021 List: Liste top 10:2021
          A01 Broken Access Control: A01 Contrôles d'accès défaillants
          A02 Cryptographic Failures: A02 Défaillances cryptographiques
          A03 Injection: A03 Injection
          A04 Insecure Design: A04 Conception non sécurisée
          A05 Security Misconfiguration: A05 Mauvaise configuration de sécurité
          A06 Vulnerable and Outdated Components: A06 Composants vulnérables et obsolètes
          A07 Identification and Authentication Failures: A07 Identification et authentification de mauvaise qualité
          A08 Software and Data Integrity Failures: A08 Manque d'intégrité des données et du logiciel
          A09 Security Logging and Monitoring Failures: A09 Carence des systèmes de contrôle et de journalisation
          A10 Server Side Request Forgery (SSRF): A10 Falsification de requête côté serveur (SSRF)
          Next Steps: Étapes suivantes
        id:
          Home: Beranda
          Notice: Pemberitahuan
          Introduction: Pengenalan
          How to use the OWASP Top 10 as a standard: Bagaimana cara menggunakan OWASP Top 10 sebagai sebuah standarisasi
          How to start an AppSec program with the OWASP Top 10: Bagaimana cara untuk memulai program AppSec dengan OWASP Top 10
          About OWASP: Tentang OWASP
          Top 10:2021 List: Daftar Top 10:2021
          A01 Broken Access Control: A01 Kerusakan Akses Kontrol
          A02 Cryptographic Failures: A02 Kegagalan Kriptografi
          A03 Injection: A03 Injeksi
          A04 Insecure Design: A04 Insecure Design
          A05 Security Misconfiguration: A05 Kesalahan Konfigurasi Keamanan
          A06 Vulnerable and Outdated Components: A06 Komponen yang Rentan dan Kedaluwarsa
          A07 Identification and Authentication Failures: A07 Kegagalan Identifikasi dan Otentikasi
          A08 Software and Data Integrity Failures: A08 Kegagalan Integritas Data dan Perangkat Lunak
          A09 Security Logging and Monitoring Failures: A09 Kegagalan dalam Keamanan Logging dan Monitoring
          A10 Server Side Request Forgery (SSRF): A10 Server-Side Request Forgery (SSRF)
          Next Steps: Langkah Selanjutnya
        it:
          Home: Casa
          Notice: Avvisi
          Introduction: Introduzione
          How to use the OWASP Top 10 as a standard: Come utilizzare la OWASP Top 10 come standard
          How to start an AppSec program with the OWASP Top 10: Come avviare un programma di AppSec con la OWASP Top 10
          About OWASP: A proposito di OWASP
          Top 10:2021 List: Lista top 10:2021
          A01 Broken Access Control: A01 Broken Access Control
          A02 Cryptographic Failures: A02 Cryptographic Failures
          A03 Injection: A03 Injection
          A04 Insecure Design: A04 Insecure Design
          A05 Security Misconfiguration: A05 Security Misconfiguration
          A06 Vulnerable and Outdated Components: A06 Vulnerable and Outdated Components
          A07 Identification and Authentication Failures: A07 Identification and Authentication Failures
          A08 Software and Data Integrity Failures: A08 Software and Data Integrity Failures
          A09 Security Logging and Monitoring Failures: A09 Security Logging and Monitoring Failures
          A10 Server Side Request Forgery (SSRF): A10 Server Side Request Forgery (SSRF)
          Next Steps: Passi seguenti
        ja:
          Home: ホーム
          Notice: 注意事項
          Introduction: 導入
          How to use the OWASP Top 10 as a standard: OWASP Top 10 をスタンダードとして使うには
          How to start an AppSec program with the OWASP Top 10: OWASP Top 10 を使ってアプリケーションセキュリティプログラムを始めるには
          About OWASP: OWASPについて
          Top 10:2021 List: Top 10:2021 一覧
          A01 Broken Access Control: A01 アクセス制御の不備
          A02 Cryptographic Failures: A02 暗号化の失敗
          A03 Injection: A03 インジェクション
          A04 Insecure Design: A04 安全が確認されない不安な設計
          A05 Security Misconfiguration: A05 セキュリティの設定ミス
          A06 Vulnerable and Outdated Components: A06 脆弱で古くなったコンポーネント
          A07 Identification and Authentication Failures: A07 識別と認証の失敗
          A08 Software and Data Integrity Failures: A08 ソフトウェアとデータの整合性の不具合
          A09 Security Logging and Monitoring Failures: A09 セキュリティログとモニタリングの失敗
          A10 Server Side Request Forgery (SSRF): A10 サーバーサイドリクエストフォージェリ (SSRF)
          Next Steps: Next Steps
        pt_BR:
          Home: Início
          Notice: Notas
          Introduction: Introdução
          How to use the OWASP Top 10 as a standard: Como usar o OWASP Top 10 como padrão
          How to start an AppSec program with the OWASP Top 10: Como iniciar um programa AppSec com o OWASP Top 10
          About OWASP: Sobre OWASP
          Top 10:2021 List: Lista top 10:2021
          A01 Broken Access Control: A01 Quebra de Controle de Acesso
          A02 Cryptographic Failures: A02 Falhas Criptográficas
          A03 Injection: A03 Injeção
          A04 Insecure Design: A04 Design Inseguro
          A05 Security Misconfiguration: A05 Configuração Incorreta de Segurança
          A06 Vulnerable and Outdated Components: A06 Componentes Vulneráveis e Desatualizados
          A07 Identification and Authentication Failures: A07 Falhas de identificação e autenticação
          A08 Software and Data Integrity Failures: A08 Falhas de Software e Integridade de Dados
          A09 Security Logging and Monitoring Failures: A09 Falhas de registro e monitoramento de segurança
          A10 Server Side Request Forgery (SSRF): A10 Falsificação de Solicitação do Lado do Servidor (SSRF)
          Next Steps: Próximos passos
        zh_TW:
          Home: 首頁
          Notice: 注意事項
          Introduction: OWASP 2021 介紹
          How to use the OWASP Top 10 as a standard: 如何正確使用 OWASP Top 10 為標準
          How to start an AppSec program with the OWASP Top 10: 如何使用 OWASP Top 10 啟動 AppSec
          About OWASP: OWASP 相關
          Top 10:2021 List: Top 10:2021 名單
          A01 Broken Access Control: A01 權限控制失效
          A02 Cryptographic Failures: A02 加密機制失效
          A03 Injection: A03 注入式攻擊
          A04 Insecure Design: A04 不安全設計
          A05 Security Misconfiguration: A05 安全設定缺陷
          A06 Vulnerable and Outdated Components: A06 危險或過舊的元件
          A07 Identification and Authentication Failures: A07 認證及驗證機制失效
          A08 Software and Data Integrity Failures: A08 軟體及資料完整性失效
          A09 Security Logging and Monitoring Failures: A09 資安記錄及監控失效
          A10 Server Side Request Forgery (SSRF): A10 伺服端請求偽造
          Next Steps: 下一步
        zh_CN:
          Home: 首頁
          Notice: 注意事项
          Introduction: OWASP 2021 介紹
          How to use the OWASP Top 10 as a standard: 如何正确使用 OWASP Top 10 为标准
          How to start an AppSec program with the OWASP Top 10: 如何使用 OWASP Top 10 启动 AppSec
          About OWASP: OWASP 相关
          Top 10:2021 List: Top 10:2021 名单
          A01 Broken Access Control: A01 权限控制失效
          A02 Cryptographic Failures: A02 加密机制失效
          A03 Injection: A03 注入式攻击
          A04 Insecure Design: A04 不安全设计
          A05 Security Misconfiguration: A05 安全设定缺陷
          A06 Vulnerable and Outdated Components: A06 危险或过旧的组件
          A07 Identification and Authentication Failures: A07 认证及体验机制失效
          A08 Software and Data Integrity Failures: A08 软体及资料完整性失效
          A09 Security Logging and Monitoring Failures: A09 安全记录及监控失效
          A10 Server Side Request Forgery (SSRF): A10 服务端请求伪造
          Next Steps: 下一步
  - macros:     # needs to be the last plugin to export the final osib-YAML file for all languages
     module_name: '../osib/osib_macro'
     include_dir: '../osib/include'
     verbose: false                                                  # debug
     on_error_fail: true
extra:
  alternate:                                                         # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector
    - name: en - English
      link: ./
      lang: en
    - name: ar - ﺎﻠﻋﺮﺒﻳﺓ
      link: ./ar/
      lang: ar
    - name: de - Deutsch
      link: ./de/
      lang: de
    - name: es - Español
      link: ./es/
      lang: es
    - name: fr - Français
      link: ./fr/
      lang: fr
    - name: id - Indonesian
      link: ./id/
      lang: id
    - name: it - Italiano
      link: ./it/
      lang: it
    - name: ja - 日本語
      link: ./ja/
      lang: ja
    - name: pt_BR - Português (Brasil)
      link: ./pt_BR/
      lang: pt_BR
    - name: zh_CN - 简体中文
      link: ./zh_CN/
      lang: zh_CN
    - name: zh_TW - 繁體中文
      link: ./zh_TW/
      lang: zh_TW
  osib:
    document:     osib.owasp.top10
    version:      2021-1-0
#    document:     <osib-id>                    # e.g. osib.owasp.top10
#    version:      <version-no, no dots '.'>    # e.g. 4-0, 2021-1-0
    categories:   [document, awareness]        # list of all default categories
    default_lang: en
    yaml_file:    ../osib/include/osib.yml
    export_dir:   ../osib/export
    latest:       2                            # 2: add the latest version(s), if successor(s) exist, log an info
    debug:        0                            # debug level (0-3); default is 2
    cre:          osib.owasp.cre.1-0
    successor_texts:
      en:         successor
      de:         Nachfolger
    split_to_texts:
      en:         split to
      de:         Aufgeteilt in
